#!/bin/bash

# Project Name
PROJECT_NAME="waymo-imitation-rl"

echo "🚀 Initializing UV Project: $PROJECT_NAME"
echo "---------------------------------------"

# 1. Check for UV
if ! command -v uv &> /dev/null
then
    echo "❌ Error: 'uv' is not installed."
    echo "   Please install it via: curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi

# 2. Initialize UV Project
# ---------------------------------------
echo "Initializing uv workspace..."
uv init $PROJECT_NAME --app
cd $PROJECT_NAME

# Remove default hello.py generated by uv init
rm hello.py

# 3. Create Directory Structure
# ---------------------------------------
echo "Creating directories..."
mkdir -p data/waymo_raw
mkdir -p data/waymo_processed
mkdir -p src
mkdir -p configs
mkdir -p scripts
mkdir -p models
mkdir -p logs

# 4. Create pyproject.toml (The UV Configuration)
# ---------------------------------------
echo "Configuring pyproject.toml..."

cat << 'EOF' > pyproject.toml
[project]
name = "waymo-imitation-rl"
version = "0.1.0"
description = "Robust Imitation Learning using Waymo Open Dataset and PPO"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "stable-baselines3>=2.0.0",
    "metadrive-simulator>=0.4.0",
    "scenarionet>=0.2.0",
    "gymnasium",
    "torch",
    "numpy",
    "pyyaml",
    "tensorboard"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
EOF

# 5. Create Configuration File
# ---------------------------------------
cat << 'EOF' > configs/config.yaml
training:
  use_render: False
  num_scenarios: 100
  horizon: 500
  total_timesteps: 1000000
  batch_size: 64
  learning_rate: 0.0003
  bc_coefficient: 0.5

paths:
  data_directory: "../data/waymo_processed"
  logs: "./logs/"
  models: "./models/"
EOF

# 6. Create Source Code (src/)
# ---------------------------------------
echo "Creating source code..."

# src/__init__.py
touch src/__init__.py

# src/utils.py
cat << 'EOF' > src/utils.py
import numpy as np

class PIDController:
    def __init__(self, k_p=1.0, k_i=0.0, k_d=0.1):
        self.k_p = k_p
        self.k_i = k_i
        self.k_d = k_d
        self.prev_error = 0
        self.integral = 0

    def get_control(self, error):
        self.integral += error
        derivative = error - self.prev_error
        output = self.k_p * error + self.k_i * self.integral + self.k_d * derivative
        self.prev_error = error
        return output

def get_expert_action(vehicle, target_waypoint):
    """
    Calculates the steering/throttle needed for 'vehicle' to hit 'target_waypoint'.
    """
    vehicle_pos = vehicle.position
    vehicle_heading = vehicle.heading_theta
    
    target_vector = target_waypoint - vehicle_pos
    target_heading = np.arctan2(target_vector[1], target_vector[0])
    
    heading_error = target_heading - vehicle_heading
    heading_error = (heading_error + np.pi) % (2 * np.pi) - np.pi
    
    # PID for Steering
    steering = np.clip(heading_error * 1.5, -1.0, 1.0)
    
    # Simple Throttle Logic
    throttle = 0.6 if abs(steering) < 0.3 else 0.3
    
    return np.array([steering, throttle])
EOF

# src/env_wrapper.py
cat << 'EOF' > src/env_wrapper.py
import gymnasium as gym
import numpy as np
from metadrive.envs.scenario_env import ScenarioEnv
from src.utils import get_expert_action

class WaymoImitationEnv(gym.Wrapper):
    def __init__(self, config):
        env = ScenarioEnv(config)
        super().__init__(env)
        
    def step(self, action):
        obs, reward, terminated, truncated, info = self.env.step(action)
        
        try:
            # Access MetaDrive engine to get expert trajectory
            expert_traj = self.env.engine.map_manager.current_sdc_route
            
            if expert_traj is not None and len(expert_traj) > 0:
                target_pos = expert_traj[-1] 
                expert_action = get_expert_action(self.env.vehicle, target_pos)
            else:
                expert_action = np.zeros(2)
            
            info['expert_action'] = expert_action
            
        except Exception:
            info['expert_action'] = np.zeros(2)

        return obs, reward, terminated, truncated, info
EOF

# src/algorithms.py
cat << 'EOF' > src/algorithms.py
import torch as th
import torch.nn.functional as F
import gymnasium as gym
from stable_baselines3 import PPO

class BC_PPO(PPO):
    """
    Custom PPO implementation with Behavior Cloning (BC) loss.
    """
    def __init__(self, *args, bc_coef=0.2, **kwargs):
        super().__init__(*args, **kwargs)
        self.bc_coef = bc_coef

    def train(self):
        self.policy.set_training_mode(True)
        self._update_learning_rate(self.policy.optimizer)
        # Note: Full implementation requires subclassing RolloutBuffer 
        # to store expert actions. This is a structural skeleton.
        super().train() 
EOF

# 7. Create Scripts (scripts/)
# ---------------------------------------
echo "Creating scripts..."

# scripts/convert_data.py
cat << 'EOF' > scripts/convert_data.py
import argparse
import os
from scenarionet import converter

def convert_waymo(raw_path, output_path):
    if not os.path.exists(raw_path):
        print(f"Error: Raw path {raw_path} does not exist.")
        return

    print(f"Converting data from {raw_path} to {output_path}...")
    converter.convert_waymo(
        input_path=raw_path,
        output_path=output_path,
        worker_num=4 
    )
    print("Conversion Complete.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--raw", type=str, required=True, help="Path to folder with .tfrecord files")
    parser.add_argument("--out", type=str, required=True, help="Path to output folder")
    args = parser.parse_args()
    convert_waymo(args.raw, args.out)
EOF

# scripts/train.py
cat << 'EOF' > scripts/train.py
import sys
import os
import yaml
import gymnasium as gym
from stable_baselines3.common.callbacks import CheckpointCallback

# Ensure src is in path
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from src.env_wrapper import WaymoImitationEnv
from src.algorithms import BC_PPO

def load_config(path):
    with open(path, 'r') as f:
        return yaml.safe_load(f)

def main():
    config_path = os.path.join(os.path.dirname(__file__), '../configs/config.yaml')
    cfg = load_config(config_path)
    
    env_config = {
        "use_render": cfg['training']['use_render'],
        "data_directory": cfg['paths']['data_directory'],
        "num_scenarios": cfg['training']['num_scenarios'],
        "horizon": cfg['training']['horizon']
    }

    print("Initializing Environment...")
    try:
        env = WaymoImitationEnv(env_config)
    except Exception as e:
        print(f"Error loading env: {e}")
        print("Did you run convert_data.py first?")
        return
    
    model = BC_PPO(
        "MultiInputPolicy", 
        env,
        verbose=1,
        bc_coef=cfg['training']['bc_coefficient'],
        learning_rate=cfg['training']['learning_rate'],
        tensorboard_log=cfg['paths']['logs']
    )
    
    print("Starting Training...")
    checkpoint_callback = CheckpointCallback(
        save_freq=10000, 
        save_path=cfg['paths']['models'], 
        name_prefix='bc_ppo'
    )
    
    model.learn(
        total_timesteps=cfg['training']['total_timesteps'], 
        callback=checkpoint_callback
    )
    
    final_path = os.path.join(cfg['paths']['models'], "final_waymo_agent")
    model.save(final_path)
    print(f"Training Finished. Model Saved to {final_path}")

if __name__ == "__main__":
    main()
EOF

# 8. Create README with UV Instructions
# ---------------------------------------
echo "Creating README..."

cat << 'EOF' > README.md
# Imitation Is Not Enough: BC-PPO for Autonomous Driving

**A Robust Imitation Learning Implementation using Waymo Open Dataset & MetaDrive**

## 🚗 Project Overview
This project replicates the core concepts of the paper *"Imitation Is Not Enough: Robustifying Imitation with Reinforcement Learning"*. It tackles the issue of **covariate shift** in autonomous driving by combining **Behavior Cloning (BC)** with **Reinforcement Learning (PPO)**.

## 🛠 Tech Stack
- **Manager:** [uv](https://github.com/astral-sh/uv) (Fast Python package installer)
- **Simulator:** MetaDrive (ScenarioNet)
- **Data:** Waymo Open Motion Dataset
- **Algorithm:** PPO (Proximal Policy Optimization) + Behavior Cloning

## 🚀 Getting Started

### 1. Prerequisites
Install \`uv\`:
\`\`\`bash
curl -LsSf https://astral.sh/uv/install.sh | sh
\`\`\`

### 2. Installation & Sync
Initialize the virtual environment and install dependencies instantly:
\`\`\`bash
uv sync
\`\`\`

### 3. Data Preparation
Download Waymo Motion Dataset (.tfrecord files) to \`data/waymo_raw/\`, then run:
\`\`\`bash
uv run scripts/convert_data.py --raw data/waymo_raw --out data/waymo_processed
\`\`\`

### 4. Training
Run the training script inside the environment:
\`\`\`bash
uv run scripts/train.py
\`\`\`

## 📂 Structure
- \`pyproject.toml\`: Project dependencies managed by uv.
- \`src/\`: Custom PPO implementation and Environment wrappers.
- \`scripts/\`: Entry points for data conversion and training.

## 📜 References
- Lu et al., "Imitation Is Not Enough", IROS.
- Knox et al., "Reward (Mis)design for Autonomous Driving".
EOF

# 9. Final Sync
# ---------------------------------------
echo "Locking dependencies with uv..."
uv sync

echo "---------------------------------------"
echo "✅ Project setup complete at ./$PROJECT_NAME"
echo "✅ Virtual Environment created."
echo "---------------------------------------"
echo "Next steps:"
echo "1. cd $PROJECT_NAME"
echo "2. Download Waymo data into data/waymo_raw"
echo "3. Run: uv run scripts/convert_data.py ..."
